apiVersion: v1
kind: Service
metadata:
  name: scala-akka-kubernetes-example-service
spec:
  selector:
    app: scala-akka-kubernetes-example
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090